### ISSUE TITLE
[BUG] Running example

### ISSUE THREAD

**Issue by Nucleon729** [amazon-science/chronos-forecasting#135]
Hi,

I get this error when I run the example snipet code on macOS M1 Max:

> ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation.

here is the full report:

```

Python 3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd  # requires: pip install pandas
>>> import torch
>>> from chronos import ChronosPipeline
>>> 
>>> pipeline = ChronosPipeline.from_pretrained(
...     "amazon/chronos-t5-small",
...     device_map="mps",  # use "cpu" for CPU inference and "mps" for Apple Silicon
...     torch_dtype=torch.bfloat16,
... )
/opt/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
>>> 
>>> df = pd.read_csv("https://raw.githubusercontent.com/AileenNielsen/TimeSeriesAnalysisWithPython/master/data/AirPassengers.csv")
>>> 
>>> # context must be either a 1D tensor, a list of 1D tensors,
>>> # or a left-padded 2D tensor with batch as the first dimension
>>> # forecast shape: [num_series, num_samples, prediction_length]
>>> forecast = pipeline.predict(
...     context=torch.tensor(df["#Passengers"]),
...     prediction_length=12,
...     num_samples=20,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.11/site-packages/chronos/chronos.py", line 512, in predict
    samples = self.model(
              ^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/chronos/chronos.py", line 336, in forward
    preds = self.model.generate(
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/transformers/generation/utils.py", line 1543, in generate
    self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
  File "/opt/anaconda3/lib/python3.11/site-packages/transformers/generation/utils.py", line 1403, in _prepare_special_tokens
    raise ValueError(
ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation.
```

Any idea how to fix that ?

Kind regards,

**Comment by abdulfatir** [comment]
@Nucleon729 what's your transformers version?

**Comment by Nucleon729** [comment]
Hi @abdulfatir ,

it's:
```
>>> print(transformers.__version__)
4.41.0

```

**Comment by abdulfatir** [comment]
This is an issue in `transformers==4.41.0`. Please upgrade.
