### ISSUE TITLE
GluonTSDataError: Error "unhashable type: 'numpy.ndarray'" occurred, when reading field "start"

### ISSUE THREAD

**Issue by topeolatunji19** [amazon-science/chronos-forecasting#153]
**Bug report checklist**
Hello! I was attempting to follow the example pretraining exercise. However, when I run the training.py script, I get a GluonTSData Error. The error seems to be coming from training.py 

**Describe the bug**
This is the error
```
2024-07-17 11:03:42,855 - /home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py - INFO - Initializing model
2024-07-17 11:03:42,855 - /home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py - INFO - Using pretrained initialization from amazon/chronos-t5-base
The speedups for torchdynamo mostly come wih GPU Ampere or higher and which is not detected here.
max_steps is given, it will override any value given in num_train_epochs
2024-07-17 11:03:44,993 - /home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py - INFO - Training
  0%|                                                                                                                                                              | 0/200000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py", line 692, in <module>
    app()
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer/core.py", line 661, in main
    return _main(
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/typer_config/decorators.py", line 92, in wrapped
    return cmd(*args, **kwargs)
  File "/home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py", line 679, in main
    trainer.train()
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/transformers/trainer.py", line 2230, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/accelerate/data_loader.py", line 677, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/accelerate/data_loader.py", line 631, in _fetch_batches
    batches.append(next(iterator))
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
gluonts.exceptions.GluonTSDataError: Caught GluonTSDataError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/dataset/common.py", line 291, in __call__
    data[self.name] = _as_period(data[self.name], self.freq)
TypeError: unhashable type: 'numpy.ndarray'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py", line 241, in __iter__
    for element in self.base_dataset:
  File "/home/ubuntu/chronos-pretraining/chronos-forecasting/scripts/training/train.py", line 491, in __iter__
    yield self.to_hf_format(next(iterators[idx]))
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/transform/_base.py", line 111, in __iter__
    yield from self.transformation(
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/transform/_base.py", line 186, in __call__
    for data_entry in data_it:
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/transform/_base.py", line 186, in __call__
    for data_entry in data_it:
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/itertools.py", line 85, in __iter__
    for el in self.iterable:
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/dataset/common.py", line 424, in __call__
    data = t(data)
  File "/home/ubuntu/chronos-pretraining/myenv/lib/python3.10/site-packages/gluonts/dataset/common.py", line 293, in __call__
    raise GluonTSDataError(
gluonts.exceptions.GluonTSDataError: Error "unhashable type: 'numpy.ndarray'" occurred, when reading field "start"

  0%|          | 0/200000 [00:00<?, ?it/s]
  ```
  
This is the config file
```
training_data_paths:
- "noise-data.arrow"
probability:
- 1.0
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: amazon/chronos-t5-base
model_type: seq2seq
random_init: false
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
```

**Expected behavior**
I expected the pretraining to run successfully.

**To reproduce**
1. Install the chronos package with the training extra.
2. Generate sample time series and convert it to an arrow format per the example (https://github.com/amazon-science/chronos-forecasting/tree/main/scripts)
3. Modify training/configs/chronos-t5-base.yaml to add the noise-data.arrow file path with 1.0 probability
4. Cloned the chronos-forecasting repository
5. Run the training command pointing to the config:
`CUDA_VISIBLE_DEVICES=0 python chronos-forecasting/scripts/training/train.py --config chronos-t5-base-finetuned.yaml`

**Environment description**
Operating system: Ubuntu 24.04
Python version: Python 3.10.14
CUDA version: 11.4
PyTorch version: 2.0.0+cu117
HuggingFace transformers version: 4.42.4
HuggingFace accelerate version: 0.32.1

**Comment by abdulfatir** [comment]
@topeolatunji19 can you share how exactly you converted the data into arrow format?

**Comment by topeolatunji19** [comment]
I used this function

```
def convert_to_arrow(
    path: Union[str, Path],
    time_series: Union[List[np.ndarray], np.ndarray],
    start_times: Optional[Union[List[np.datetime64], np.ndarray]] = None,
    compression: str = "lz4",
):
    if start_times is None:
        # Set an arbitrary start time
        start_times = [np.datetime64("2000-01-01 00:00", "s")] * len(time_series)

    assert len(time_series) == len(start_times)

    print(start_times)

    dataset = [
        {"start": start, "target": ts} for ts, start in zip(time_series, start_times)
    ]
    ArrowWriter(compression=compression).write_to_file(
        dataset,
        path=path,
    )
```

**Comment by abdulfatir** [comment]
I meant how are you using this function. What are you passing as `start_times`?

**Comment by topeolatunji19** [comment]
This is how I pass the start times.
`convert_to_arrow("./noise-data.arrow", time_series=time_series, start_times=start_times)`

 I printed out the first 5 of the start_times
 
```[[numpy.datetime64('2024-06-20T08:41:00')], [numpy.datetime64('2024-06-20T08:44:00')], [numpy.datetime64('2024-06-20T08:41:00')], [numpy.datetime64('2024-06-20T08:41:00')], [numpy.datetime64('2024-06-20T08:42:00')]]```

I use multiple start_times because I have multiple time_series

**Comment by abdulfatir** [comment]
As specified in the type signature (`Optional[Union[List[np.datetime64], np.ndarray]] `), `start_times` should be a list of `np.datetime64` or a 1-d numpy array of datetimes. What you have here is a list of lists. Could you try flattening this list and see if it works? Basically,

```py
[numpy.datetime64('2024-06-20T08:41:00'), numpy.datetime64('2024-06-20T08:44:00'), numpy.datetime64('2024-06-20T08:41:00'), numpy.datetime64('2024-06-20T08:41:00'), numpy.datetime64('2024-06-20T08:42:00')]
```

**Comment by abdulfatir** [comment]
You can try turning off compilation by `--no-torch-compile` flag.
